name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 7 * * *'
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "20"
                feed_list: "https://medium.com/feed/tag/bug-bounty"
                template: "$newline - $randomEmoji(💯)$date - [$title]($url) $newline"
                date_format: "mmmm d, yyyy"
                remove_duplicates: "true"
